name: Deploy Templatized Data Environment

on:
  push:
    branches: [staging, main]
  pull_request:
    types: [closed]
    branches: [staging, main]

jobs:
  deploy_data_environment:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"

      - name: Configure Snowflake connection
        run: |
          snow connection add github_action_conn \
            --account ${{ env.SNOWFLAKE_ACCOUNT }} \
            --user ${{ env.SNOWFLAKE_USER }} \
            --password ${{ env.SNOWFLAKE_PASSWORD }} \
            --role ACCOUNTADMIN \
            --warehouse COMPUTE_WH \
            --database COURSE_REPO \
            --schema PUBLIC \
            --default

          snow connection test github_action_conn

      - name: Fetch latest changes
        run: snow git fetch course_repo.public.advanced_data_engineering_snowflake

      - name: Deploy templates
        run: |
          snow git execute @advanced_data_engineering_snowflake/branches/${GITHUB_REF_NAME}/module-1/hamburg_weather/pipeline/data/ \
          -D "env='${{ env.DEPLOY_ENV }}'" \
          --database=COURSE_REPO \
          --schema=PUBLIC
